server:
  port: 8081

#hdfs:
#  hdfsPath: hdfs://192.168.146.130:8020
#  hdfsName: node01
#  hdfsUser: root

spring:
  datasource:
    name : Elebus
    url : jdbc:mysql://localhost:3306/janal?characterEncoding=UTF-8&useSSL=false&useUnicode=true&serverTimezone=UTC&allowMultiQueries=true
    username : root
    password : root
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

file:
#  upload-dir: ./JournalAnalysisDEMO/uploads
  upload-dir: ./uploads

